name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image from DockerHub
      run: docker pull manukrishna333/my-node-app:latest

    - name: Deploy to staging
      run: |
        docker stop my-node-app || true
        docker rm my-node-app || true
        docker run -d --name my-node-app -p 8080:3000 manukrishna333/my-node-app:latest

    - name: Wait for the application to start
      run: sleep 10

    - name: Check Docker status
      run: |
        docker --version
        docker ps -a

    - name: Verify deployment
      run: |
        for i in {1..5}; do
          curl -f http://127.0.0.1:8080 && break
          echo "Attempt $i failed, retrying in 5 seconds..."
          sleep 5
        done

